# Generated by Django 3.1.3 on 2021-02-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='classes')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('token', models.CharField(default='N6X2fPFZoCdRhaMsWACNtpdOPals1Z', max_length=30, unique=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('profilePicture', models.FileField(upload_to='Admins')),
                ('classes', models.ManyToManyField(to='KHATF.Classes')),
            ],
        ),
    ]
