# Generated by Django 3.1.3 on 2021-02-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profilePicture',
            field=models.ImageField(upload_to='Admins'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='0qi8Y35myhVzYhRbDurwdAOz1FmwAu', max_length=30, unique=True),
        ),
    ]
