# Generated by Django 3.1.3 on 2021-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0002_auto_20210209_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='r7qY5DiRd1EMxRm9hyF41xBTHhuCdA', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.ImageField(upload_to='classes'),
        ),
    ]
