# Generated by Django 3.1.3 on 2021-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0003_auto_20210209_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profilePicture',
            field=models.FileField(upload_to='Admins'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='oswvKVn63HZdQgnXCEmXzUbHvhIsx0', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.FileField(upload_to='classes/'),
        ),
    ]
