# Generated by Django 3.1.3 on 2021-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0004_auto_20210210_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='vIujrKOZtwaIH7C3gzDsDzPEfE9oRJ', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.FileField(upload_to='classes/', verbose_name='RAXmO9dqGercCI5T0aUlPyvNpxxFIuJmuikHjMMp0h8EohljbT'),
        ),
    ]
