# Generated by Django 3.1.3 on 2021-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0005_auto_20210210_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='UD29GmB6eXhKfJDm0J3G5bFsU4aiNcR1ICeQgqfmwFJgJlasTf', max_length=50)),
                ('code', models.CharField(default='277219376796', max_length=6)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='profilePicture',
            field=models.FileField(upload_to='Admins', verbose_name='LG2gCNfIfohwLjGrPgO24ycMWcZDo6ZHIhERYKlwrRAddjxafU'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='rZ35rb7nQ3xYSSs9l8qR6PwSO9AH1Z', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.FileField(upload_to='classes/', verbose_name='wzeQzQV2FcXbZPuwnZfZKYwqV24sQ6Gvv5NEkQNjFUxh5eO74P'),
        ),
    ]
