# Generated by Django 3.1.3 on 2021-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0006_auto_20210210_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='classes',
            field=models.ManyToManyField(blank=True, to='KHATF.Classes'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profilePicture',
            field=models.FileField(upload_to='Admins', verbose_name='Ez5aGxl2RmEmCo65K4BWWswh9jgJzNmWGqCgLJYEBrABTr1JSP'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='NxtD6E5cdSKgdzMKWugPfz42U3UHbr', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.FileField(upload_to='classes/', verbose_name='TCImc56ggKoQgSpb9xiioVnPW3LPMJ69G14FCPp5RGkTkLNTGw'),
        ),
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(default='944783892495', max_length=6),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='F8XBrvgsHU310n3nnHONlN29WOC2oXCuBcxyqUj7nMzxmsrz7c', max_length=50),
        ),
    ]
