# Generated by Django 3.1.3 on 2021-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0007_auto_20210210_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profilePicture',
            field=models.FileField(blank=True, upload_to='Admins', verbose_name='dwW8LK54VZPSIi3kdl9WnSIiRK5aAj0kOD9eKFAH8W3G2D7vEd'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='yqk434yv9FNTIxfCBx25nwMwq8yz2S', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.FileField(upload_to='classes/', verbose_name='xaXEYM3hhvsN6GWnBZKdA66vyFiFMEG93wgnKkoHDnUUWEpHH7'),
        ),
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(default='228647226732', max_length=6),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='PJQQEf4pVqbsrhYvoh4GQJimKbCEWLwRXXugCv4kDeFW7RWzIU', max_length=50),
        ),
    ]
