# Generated by Django 3.1.3 on 2021-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHATF', '0008_auto_20210211_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default='کاربر786393', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profilePicture',
            field=models.FileField(blank=True, upload_to='Admins', verbose_name='VEnuTE1WJT2LXN3ppsLJxWsfeQXsXcrrIQVbPX4sZlegprGEGz'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='token',
            field=models.CharField(default='f6rAokpZ3zXF6Q3SNgod4b6BnEjfD4', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Image',
            field=models.FileField(upload_to='classes/', verbose_name='xQjRE5jhhFlIqQFjBFF2PyhEaBionZwow2EPUTXVUwYUVVXR6e'),
        ),
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(default='676569663866', max_length=6),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='RUUiXEdGBJBqbwZWoox7Q9IRNSLpYob7dPtSv3859Wi6nPdnkP', max_length=50),
        ),
    ]
